# Server configuration
host: "0.0.0.0"
policy_endpoint: "/policy-prediction"  # API endpoint for policy predictions
value_endpoint: "/value-prediction"  # API endpoint for value predictions

# Model configuration
policy_model: "AngelRaychev/policy_iteration_"
value_model: "AngelRaychev/value_iteration_"

# MCTS parameters
branch_factor: 3
max_expansions: 20
temperature: 1.0
c_explore: 0.3
batch_size: 50

# Target data generation parameters
target_examples_train: 10000
target_examples_dev: 1000

# Data paths
train_questions_path: "questions/train.txt"
dev_questions_path: "questions/dev.txt"

# Output paths for generated data
policy_data_path: "data/mcts_generated/policy/iteration_"
value_data_path: "data/mcts_generated/value/iteration_"

# Runtime configuration
stats_interval: 30 