# Value function finetuning
train_arguments:
  device: "cuda"
  model_function: "value"
  model_name: "HuggingFaceTB/SmolLM2-135M"
  save_model_name: "smol-lm-135M"
  output_dir: "/scaling_laws_baseline/models/iter_1/value/"
  eval_steps: 10
  logging_steps: 20
  save_steps: 50
  max_epochs: 10
  batch_size: 8
  warmup_steps: 100
  max_grad_norm: 1.0
  weight_decay: 0.01
  base_lr: 2e-5
  head_lr: 2e-5
  logging_steps: 5
  evaluation_strategy: "steps"
  use_mps_device: false
  hub_model_id: "smol-lm-135M"
  training_data_file: "/scaling_laws_baseline/code/data/iter1/135_135/value_ds"
  validation_data_file: "/scaling_laws_baseline/code/data/iter1/135_135/value_ds"
  patience: 3
  seed: 42
  gradient_accumulation_steps: 4