# Model and dataset configuration
model_name: AngelRaychev/3B-sos-iteration_
revision: None
hub_model_id: AngelRaychev/3B-sos-iteration_
dataset_file: data/sos/iteration_
plot_path: logs/sos/training/iteration_
device: cuda

# Optimization parameters
lr_scheduler_type: "constant"

# Logging parameters
logging_steps: 1

