# Model and dataset configuration
model_name: AngelRaychev/policy_iteration_0
device: cuda
hub_model_id: AngelRaychev/policy_iteration_1
dataset_file: data/pre_generated/policy

# Optimization parameters
learning_rate: 2e-4  
lr_scheduler_type: "reduce_lr_on_plateau"
optimizer: "adamw_torch"
accumulation_steps: 4
max_grad_norm: 1.0

# ReduceLROnPlateau scheduler parameters
lr_scheduler_factor: 0.5    
lr_scheduler_patience: 1    
lr_scheduler_threshold: 0.01 
lr_scheduler_min_lr: 1e-6    

# Regularization parameters
weight_decay: 0.01

# Convergence criteria
logging_steps: 10
eval_steps: 100
patience: 5
improvement_tolerance: 0.001
