# Model and dataset configuration
model_name: AngelRaychev/value_iteration_1
device: cuda
hub_model_id: AngelRaychev/value_iteration_2
dataset_file: data/mcts_generated/value/value

# Optimization parameters
learning_rate: 1e-4
lr_scheduler_type: "reduce_lr_on_plateau"
optimizer: "adamw_torch"
accumulation_steps: 4
max_grad_norm: 1.0

# Custom learning rate scheduler parameters
lr_scheduler_factor: 0.5
lr_scheduler_patience: 1
lr_scheduler_threshold: 0.001

# Regularization parameters
weight_decay: 0.01

# Convergence criteria
logging_steps: 5
eval_steps: 10
patience: 3
improvement_tolerance: 0.01
