# Model and dataset configuration
model_name: AngelRaychev/0.5B-value-iteration_
revision: None
hub_model_id: AngelRaychev/0.5B-value-iteration_
dataset_file: data/value/iteration_
plot_path: logs/training/value/iteration_
device: cuda

# Optimization parameters
learning_rate: 5e-6
per_device_train_batch_size: 256
lr_scheduler_type: "constant"
gradient_accumulation_steps: 1

# Convergence criteria
logging_steps: 20
