# Model and dataset configuration
model_name: AngelRaychev/value_iteration_
device: cuda
hub_model_id: AngelRaychev/value_iteration_
dataset_file: data/mcts_generated/value/iteration_

# Optimization parameters
learning_rate: 5e-5
lr_scheduler_type: "reduce_lr_on_plateau"
optimizer: "adamw_torch"
accumulation_steps: 4
max_grad_norm: 1.0

# Custom learning rate scheduler parameters
lr_scheduler_factor: 0.5
lr_scheduler_patience: 1
lr_scheduler_threshold: 0.001

# Regularization parameters
weight_decay: 0.01

# Convergence criteria
logging_steps: 10
eval_steps: 10
patience: 8
improvement_tolerance: 0.001
