# The rest of params are defined in scripts_mcts/train_policy.py

# Model and dataset configuration
model_name: AngelRaychev/1.5B-policy-iteration_
revision: None
hub_model_id: AngelRaychev/1.5B-policy-iteration_
dataset_file: data/policy/iteration_
plot_path: logs/mcts/training/policy/iteration_
device: cuda

# Optimization parameters
lr_scheduler_type: "constant"

# Logging parameters
logging_steps: 1