# Model and dataset configuration
model_name: AngelRaychev/1.5B-value-iteration_
revision: None
hub_model_id: AngelRaychev/1.5B-value-iteration_
dataset_file: data/value/iteration_
plot_path: logs/mcts/training/value/iteration_
device: cuda

# Optimization parameters
lr_scheduler_type: "constant"

# Logging parameters
logging_steps: 1
