# Model and dataset configuration
model_name: AngelRaychev/value_iteration_0
device: cuda
hub_model_id: AngelRaychev/value_iteration_1
dataset_file: data/pre_generated/value

# Optimization parameters
learning_rate: 1e-4  
lr_scheduler_type: "reduce_lr_on_plateau"
optimizer: "adamw_torch"
accumulation_steps: 8
max_grad_norm: 1.0

# ReduceLROnPlateau scheduler parameters
lr_scheduler_factor: 0.5    
lr_scheduler_patience: 10
lr_scheduler_threshold: 0.001
lr_scheduler_min_lr: 1e-6

# Regularization parameters
weight_decay: 0.01

# Convergence criteria
logging_steps: 10
eval_steps: 50
patience: 3
improvement_tolerance: 0.05
