# Server configuration
host: "127.0.0.1"
policy_endpoint: "/policy-prediction"  # API endpoint for policy predictions
value_endpoint: "/value-prediction"  # API endpoint for value predictions

# Model configuration
policy_model: "AngelRaychev/0.5B-policy-iteration_"  # Base name for policy model
value_model: "AngelRaychev/0.5B-value-iteration_"    # Base name for value model

# MCTS parameters
branch_factor: 8
max_expansions: 48
temperature: 1.0
c_explore: 0.3
batch_size: 50

# Evaluation configuration
stats_interval: 30

# Data paths
test_questions_path: "questions/test.txt"
export_data_path: "evaluate/results/evaluation_iteration_"
