# The rest of params are defined in scripts_mcts/evaluate.py

# Server configuration
host: "127.0.0.1"
policy_endpoint: "/policy-prediction"  # API endpoint for policy predictions
value_endpoint: "/value-prediction"  # API endpoint for value predictions

# Model configuration
policy_model: "AngelRaychev/1.5B-policy-iteration_"  # Base name for policy model
value_model: "AngelRaychev/1.5B-value-iteration_"    # Base name for value model

# MCTS parameters
temperature: 1.0
c_explore: 0.3

# Data paths
export_data_path: "logs/mcts/evaluation/iteration_"
