# Essential configuration for model and data paths
# All training hyperparameters are determined automatically by the autonomous system

# Model identification
model:
  name: "mstojkov/sft-135-checkpoint-3000-improved_policy"
  save_name: "smol-lm-135M-iter1"
  function: "policy"

# Data paths
data:
  dataset_path: "/home/misho/data/iter1_135_ds/policy_ds"

# Output paths
output:
  save_dir: "/models/"
  hub_id: "smol-lm-135M-instruct"

# Hardware settings
hardware:
  device: "cuda"
